Landing page
FLOTUZ/boleting-full pull request #6
Opened 2023-09-13 00:19 UTC by Sirii-Dev

Creación de la landing page (solo la parte visual).

2023-09-15 04:10 UTC, FLOTUZ requested changes

2023-09-15 04:10 UTC, FLOTUZ commented on src/modules/components-landing-page/eventsCards.comonent.tsx
> +    // La url redirecciona al evento al presionar el boton de comprar boleto
Comentarios en ingles por favor

2023-09-15 04:10 UTC, FLOTUZ commented on src/modules/components-landing-page/header.component.tsx
> +          {/* para mobile */}
otro comentario en ingles

2023-09-15 04:10 UTC, FLOTUZ commented on src/modules/components-landing-page/mainEvent.component.tsx
> +// @Emmanuel, en este componente se requiere:
Anotado

2023-09-19 22:45 UTC, Sirii-Dev commented on src/modules/components-landing-page/header.component.tsx
> +          {/* para mobile */}
Listo

2023-09-19 22:55 UTC, FLOTUZ requested changes

2023-09-19 22:55 UTC, FLOTUZ commented on src/modules/components-landing-page/eventsCards.comonent.tsx
el archivo esta mal nombrado 

deberia ser:
`event-cards.component.tsx`

2023-09-19 22:55 UTC, FLOTUZ commented on src/modules/components-landing-page/mainEvent.component.tsx
El archivo esta mal nombrado

debería ser:
`main-event.component.tsx`

2023-09-20 01:15 UTC, Sirii-Dev commented on src/modules/components-landing-page/mainEvent.component.tsx
resuelto

2023-09-20 03:16 UTC, FLOTUZ approved these changes
Aguas con el naming 
Si el archivo se llama `event-card.component.tsx` deberias nombrar al componente exportado `EventCardComponent`

2023-09-20 03:16 UTC, FLOTUZ commented on src/modules/components-landing-page/event-cards.component.tsx
> +const EventCards = () => {
El componente deberia llamarse EventCardsComponent (siguiendo el estandar de nombramiento del archivo)

2023-09-20 03:36 UTC, merged